### ISSUE TITLE
Linux support would be nice

### ISSUE THREAD

**Issue by V3lectronics** [funcieqDEV/VSharp#2]
Many devs prefer Linux over Win so it would be beneficial if the project would be cross-platform. Perhaps it is as simple as making a bash install script?

**Comment by funcieqDEV** [comment]
well you are right I think that support for linux will be a good option so it will appear soon

**Comment by ff-derEchte** [comment]
it is cross platform u have the source file just intiialize a dotnet project on linux and run it

**Comment by funcieqDEV** [comment]
yeah good idea
